Modifications to support geotileplus generation in setsm-utils
PolarGeospatialCenter/pgcdemtools pull request #20
Opened 2021-04-14 19:28 UTC by clairecporter

Plus python3 upgrades

2021-04-14 19:38 UTC, clairecporter commented
@ehusby , I had to make a few modifications in dem.py to support density calculation outside the class.  All my test still pass though, so I am fairly sure the changes are invisible for any code that uses those classes.

2021-04-14 19:46 UTC, ehusby requested changes

2021-04-14 19:46 UTC, ehusby commented on lib/dem.py
> -            self.dem_edge_masked = os.path.join(self.srcdir,self.sceneid+"_dem_edge-masked.tif")
Looks like you might've accidentally removed this and the additional small block below that I added in https://github.com/PolarGeospatialCenter/pgcdemtools/pull/19?

2021-04-14 19:46 UTC, ehusby commented on lib/utils.py
> -
Same thing as the other, was this code from https://github.com/PolarGeospatialCenter/pgcdemtools/commit/d3884c8ecfa7a61d9081ea28b4ec425b56dc1124 accidentally removed?

2021-04-15 04:04 UTC, clairecporter commented
Yup. My mistake. Will fix it.

On Wed, Apr 14, 2021, 2:47 PM Erik Husby ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In lib/dem.py
> <https://github.com/PolarGeospatialCenter/pgcdemtools/pull/20#discussion_r613538055>
> :
>
> > @@ -127,15 +133,11 @@ def __init__(self,metapath,md=None):
>              self.metapath = metapath
>              self.lsf_dem = os.path.join(self.srcdir,self.sceneid+"_dem_smooth.tif")
>              self.dem = os.path.join(self.srcdir,self.sceneid+"_dem.tif")
> -            self.dem_edge_masked = os.path.join(self.srcdir,self.sceneid+"_dem_edge-masked.tif")
>
> Looks like you might've accidentally removed this and the additional small
> block below that I added in #19
> <https://github.com/PolarGeospatialCenter/pgcdemtools/pull/19>?
> ------------------------------
>
> In lib/utils.py
> <https://github.com/PolarGeospatialCenter/pgcdemtools/pull/20#discussion_r613539155>
> :
>
> > @@ -384,46 +378,3 @@ def drange(start, stop, step):
>      while r < stop:
>          yield r
>          r += step
> -
>
> Same thing as the other, was this code from d3884c8
> <https://github.com/PolarGeospatialCenter/pgcdemtools/commit/d3884c8ecfa7a61d9081ea28b4ec425b56dc1124>
> accidentally removed?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PolarGeospatialCenter/pgcdemtools/pull/20#pullrequestreview-636016022>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXRNVBJ7KR7S6ZE2II7U4TTIXWLTANCNFSM426AMFAA>
> .
>

2021-04-15 14:52 UTC, clairecporter commented
This latest commit readded those lines and also the changes in utils.py that I also reverted.  Apologies again.

2021-04-15 14:59 UTC, clairecporter commented
Wait there are some more changes that I missed.  give me a sec.

2021-04-15 19:56 UTC, ehusby commented on lib/dem.py
> +    data = utils.gdalReadAsArraySetsmSceneBand(b)
Got it! I'd messed up my test merge and got confused when looking at the working tree diff

2021-04-15 19:59 UTC, ehusby approved these changes
A+ on acing the non-proper way to resolve a merge goof, which in my opinion is way harder! ;)

2021-04-15 20:49 UTC, merged

2021-04-15 21:08 UTC, clairecporter commented
Thanks for the good grade!

On Thu, Apr 15, 2021 at 2:59 PM Erik Husby ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> A+ on acing the non-proper way to resolve a merge goof, which in my
> opinion is way harder! ;)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PolarGeospatialCenter/pgcdemtools/pull/20#pullrequestreview-637078949>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXRNVCL4ASMW3ZHOOHLLCDTI5ATVANCNFSM426AMFAA>
> .
>