Modifications to index_setsm.py to support DSP and custom paths
PolarGeospatialCenter/pgcdemtools pull request #21
Opened 2021-05-19 21:42 UTC by clairecporter

1) Index_setsm now supports writing 1 or 2 records for a downsampled product (DSP), in the current res, one in the original res, or both.
2) The --dsp-record mode-orig-status option was introduced to handle the custom status of DSP original res records when both resolutions are being handled.
3) BP and PGC path refixes were merged into a --custom-paths option and a CSS option as added
4) BP paths were updated to use the new tape bucket scheme.
5) and --np option was added to suppress progress bar use.

2021-05-19 22:35 UTC, clairecporter commented
Danny, your review is requested so you can see how your DEM ingest progess will have to change.  But no need to look it over in huge detail.  I will give you the details when we are ready to restart DEM ingest.

2021-05-20 03:14 UTC, ehusby commented on index_setsm.py
> +    parser.add_argument('--status-dsp-record-mode-orig', help='custom value for status field when dsp-record-mode is set to "orig"')
It might be a good idea to make a set of choices for this arg... just to protect against typos, yeah? ;)

2021-05-20 03:22 UTC, ehusby commented on index_setsm.py
> +    parser.add_argument('--dsp-record-mode', choices=DSP_OPTIONS.keys(), default=DEFAULT_DSP_OPTION,
The "key: value" string format item is getting lost since you only have one `{}` in the string to be formatted.

I've seen you do a lot of custom default argument help info in scripts before, so I just wanna make sure you know you could add this to your argumentparser instantiation and it will automatically show default argument values in the help info:
```
#### Set Up Arguments
parser = argparse.ArgumentParser(
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    description="build setsm DEM index"
)
```

In this case I would actually change your "Key: Value" delimiter:
`'\n'.join([k+': '+v for k,v in DSP_OPTIONS.items()])`

And then use this custom argparse formatter class, which allows for using line breaks in the help info:
```
class RawTextArgumentDefaultsHelpFormatter(argparse.ArgumentDefaultsHelpFormatter, argparse.RawTextHelpFormatter): pass
```

But the way you want the help formatted is up to you!

2021-05-20 03:28 UTC, ehusby commented on index_setsm.py
> +                                    custom_path = "{}/{}/{}/{}/{}/{}/{}/{}".format(
Probably safest to use:
```
custom_path = '/'.join([
   ...
])
```
once you start getting to so many items!

I was first thinking you could maybe use `os.path.join`, but then cringed when I thought about the case where someone tries to run this on Windows or something where the separator is `\\`

2021-05-20 03:37 UTC, ehusby requested changes
Overall looks good to me, just one string formatting issue in the index_setsm.py help info.

I've tested that I can still build a footprint from 50cm dems just fine, but haven't tested on 2m dsp scenes with any of the new functionality.

2021-05-20 15:57 UTC, clairecporter commented on index_setsm.py
> +    parser.add_argument('--status-dsp-record-mode-orig', help='custom value for status field when dsp-record-mode is set to "orig"')
It is meant to be a truly custom status.  So I don't want to proscribe the options.

2021-05-20 16:12 UTC, clairecporter commented on index_setsm.py
> +    parser.add_argument('--dsp-record-mode', choices=DSP_OPTIONS.keys(), default=DEFAULT_DSP_OPTION,
Wicked cool.

2021-05-20 17:37 UTC, clairecporter commented on index_setsm.py
> +                                    custom_path = "{}/{}/{}/{}/{}/{}/{}/{}".format(
Done for all the custom path creation

2021-05-20 17:40 UTC, clairecporter commented
> I've tested that I can still build a footprint from 50cm dems just fine, but haven't tested on 2m dsp scenes with any of the new functionality.

Regarding testing.  I have a pretty comprehensive set of tests for this script since it is so complicated in `tests/func_test_index.py`.  Happy to share the test data with you if you want.

2021-05-20 17:53 UTC, ehusby commented on index_setsm.py
> +                                    custom_path = "{}/{}/{}/{}/{}/{}/{}/{}".format(
I realized just now that the one thing string formatting has over the `'/'.join` approach is that is that all of the items must be strings or the latter approach would break.

You probably already tested that this change didn't break your unit tests? I also just scanned through the changes and it appears all of the items handed to the join are indeed strings -- no numbers.

2021-05-20 17:55 UTC, ehusby commented on index_setsm.py
> +                                    custom_path = "{}/{}/{}/{}/{}/{}/{}/{}".format(
If some items are not strings, then I guess the slightly more verbose approach would be:
```
custom_path = '/'.join([str(item) for item in [
    ...
]])
```

2021-05-20 18:19 UTC, ehusby approved these changes

2021-05-20 20:46 UTC, merged