Add scenes2strip version to strip DEM metadata handling
PolarGeospatialCenter/pgcdemtools pull request #30
Opened 2021-09-23 19:44 UTC by clairecporter

2021-09-23 20:58 UTC, ehusby requested changes

2021-09-23 20:58 UTC, ehusby commented on lib/dem.py
> +s2s_version_pattern = re.compile("Strip Metadata( \(v(?P<s2sversion>\d[\d\.]*)\))?")
I think the regex is off on the version number parsing, should instead be `"Strip Metadata( \(v(?P<s2sversion>\d+[\.\d+]*)\))?"`

2021-09-23 20:58 UTC, ehusby commented on lib/dem.py
> +                    self.avg_acqtime2 = self.avg_acqtime1
@clairecporter Do you foresee the possibility of there being a single 'STRIP_DEM_avgAcqTime' field in the mdf file? That somewhat breaks the concept of the separate average acquisition times, so I don't think we should handle it at all?

2021-09-23 20:58 UTC, ehusby commented on index_setsm.py
> +                                'AVGACQTM2': record.avg_acqtime2.strftime("%Y-%m-%d %H:%M:%S") if record.avg_acqtime2 else None,
@clairecporter I think we can get these field values rebuilt when indexing from JSONs. Let's discuss offline

2021-09-23 21:19 UTC, clairecporter commented on lib/dem.py
> +s2s_version_pattern = re.compile("Strip Metadata( \(v(?P<s2sversion>\d[\d\.]*)\))?")
They look to be the same thing to me.  In both cases, you need a digit followed by nothing or any combination of digits and periods.

2021-09-23 21:21 UTC, clairecporter commented on lib/dem.py
> +                    self.avg_acqtime2 = self.avg_acqtime1
No, but you wrote those lines...  I'm happy to take it out.

2021-09-23 21:22 UTC, ehusby commented on lib/dem.py
> +s2s_version_pattern = re.compile("Strip Metadata( \(v(?P<s2sversion>\d[\d\.]*)\))?")
Ah you're right, I forgot that the characters in the square brackets can be in any order

2021-09-23 21:22 UTC, clairecporter commented on index_setsm.py
> +                                'AVGACQTM2': record.avg_acqtime2.strftime("%Y-%m-%d %H:%M:%S") if record.avg_acqtime2 else None,
This fix was for if they are not in the MDF file from an old MDF calculated before these changes.  I don't see it happening, but I don't want the code to break if it does.

2021-09-23 21:23 UTC, ehusby commented on lib/dem.py
> +s2s_version_pattern = re.compile("Strip Metadata( \(v(?P<s2sversion>\d[\d\.]*)\))?")
No need to change. Actually I don't know how regex would handle a `\d+` in the square brackets...

2021-09-24 14:51 UTC, ehusby approved these changes

2021-09-24 17:20 UTC, clairecporter commented
@ehusby , tests updated.  I will merge if you are happy.

2021-09-24 18:49 UTC, merged

2021-09-24 19:48 UTC, ehusby commented
I don't have a "happy" emoji to react with, but anways, you already merged! All good.