Option to verify indexer wrote required records to target layer
PolarGeospatialCenter/pgcdemtools pull request #9
Opened 2020-12-04 21:18 UTC by clairecporter

I added a --check option for the indexer that verifies the presence of the required records in the target layer after writing them by building a key made up of three components:

- DEM ID (scenedemid and stripdemid, dem_id and stripdemid, or dem_id and tile depending on the mode)
- LOCATION
- INDEX_DATE
 
It is technically possible to have a false positive, but not likely given the way we use this tool. This option was built to handle instances where records are not written to postgres, but no error is thrown.  Perhaps it can help simplify Danny's ingest checks as well.

2020-12-04 21:23 UTC, ehusby approved these changes

2020-12-07 15:22 UTC, stevefoga requested changes
I just had a few comments regarding some exit returns. Otherwise the check functionality looks good!

2020-12-07 15:22 UTC, stevefoga commented on index_setsm.py
> +                    logger.info("No valid records found. No checks to perform")
Should this be log level `warning` or `error`, and exit with `-1` status? If args.check and not args.dryrun, and there's no recordids, that means there was some other larger issue above that wasn't handled, so stopping here seems logical.

2020-12-07 15:22 UTC, stevefoga commented on index_setsm.py
>      sys.exit(0)
Should there be a catch-all at the end of the function to handle `if not valid_record`? It seems like we'd want to exit with `-1` if that's ever the case, else exit `0`.

2020-12-07 20:46 UTC, clairecporter commented on index_setsm.py
> +                    logger.info("No valid records found. No checks to perform")
Sure, though I think it should be outside the `--check` functionality because it really has nothing to do with the checking.  I will add.

2020-12-07 20:52 UTC, clairecporter commented on index_setsm.py
>      sys.exit(0)
I thought that the indexer should report any issues but write whatever it could to the index.

2020-12-07 20:54 UTC, clairecporter commented on index_setsm.py
>      sys.exit(0)
I'll have it report the number that failed at least.

2020-12-07 21:03 UTC, merged